version: "3"

services:

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - api
    command: bash test/test.sh api
